name: Draft Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@master
        with:
              node-version: 14
      - name: Install Dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: Create Release Tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v0.2',
              sha: context.sha
            })
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./builds/ScrubView-linux-x64.zip
            ./builds/ScrubView-darwin-x64.zip
